[package]
org = "ballerinax"
name = "sap.businessone"
version = "1.0.0"
distribution = "2201.13.0"
authors = ["Ballerina"]
keywords = ["Name/SAP Business One", "Area/ERP & Business Operations", "Vendor/SAP", "Cost/Paid", "Type/Connector", "SAP Business One", "Service Layer", "OData", "ERP"]
repository = "https://github.com/ballerina-platform/module-ballerinax-sap.businessone"
icon = "../icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "sap.businessone-native"
version = "1.0.0"
path = "../../native/build/libs/sap.businessone-native-1.0.0.jar"
